// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProbesColumns holds the columns for the "probes" table.
	ProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled"}, Default: "disabled"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"http", "sql", "ping"}},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_heartbeat", Type: field.TypeTime, Nullable: true},
	}
	// ProbesTable holds the schema information for the "probes" table.
	ProbesTable = &schema.Table{
		Name:       "probes",
		Columns:    ProbesColumns,
		PrimaryKey: []*schema.Column{ProbesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProbesTable,
	}
)

func init() {
}
