// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Nathene/SyntheticMonitor/cmd/types"
	"github.com/Nathene/SyntheticMonitor/ent/predicate"
	"github.com/Nathene/SyntheticMonitor/ent/probe"
)

// ProbeUpdate is the builder for updating Probe entities.
type ProbeUpdate struct {
	config
	hooks    []Hook
	mutation *ProbeMutation
}

// Where appends a list predicates to the ProbeUpdate builder.
func (pu *ProbeUpdate) Where(ps ...predicate.Probe) *ProbeUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetStatus sets the "status" field.
func (pu *ProbeUpdate) SetStatus(ts types.ProbeStatus) *ProbeUpdate {
	pu.mutation.SetStatus(ts)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *ProbeUpdate) SetNillableStatus(ts *types.ProbeStatus) *ProbeUpdate {
	if ts != nil {
		pu.SetStatus(*ts)
	}
	return pu
}

// SetConfig sets the "config" field.
func (pu *ProbeUpdate) SetConfig(jm json.RawMessage) *ProbeUpdate {
	pu.mutation.SetConfig(jm)
	return pu
}

// AppendConfig appends jm to the "config" field.
func (pu *ProbeUpdate) AppendConfig(jm json.RawMessage) *ProbeUpdate {
	pu.mutation.AppendConfig(jm)
	return pu
}

// ClearConfig clears the value of the "config" field.
func (pu *ProbeUpdate) ClearConfig() *ProbeUpdate {
	pu.mutation.ClearConfig()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProbeUpdate) SetUpdatedAt(t time.Time) *ProbeUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (pu *ProbeUpdate) SetLastHeartbeat(t time.Time) *ProbeUpdate {
	pu.mutation.SetLastHeartbeat(t)
	return pu
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (pu *ProbeUpdate) SetNillableLastHeartbeat(t *time.Time) *ProbeUpdate {
	if t != nil {
		pu.SetLastHeartbeat(*t)
	}
	return pu
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (pu *ProbeUpdate) ClearLastHeartbeat() *ProbeUpdate {
	pu.mutation.ClearLastHeartbeat()
	return pu
}

// Mutation returns the ProbeMutation object of the builder.
func (pu *ProbeUpdate) Mutation() *ProbeMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProbeUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProbeUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProbeUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProbeUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProbeUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := probe.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProbeUpdate) check() error {
	if v, ok := pu.mutation.Status(); ok {
		if err := probe.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Probe.status": %w`, err)}
		}
	}
	return nil
}

func (pu *ProbeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(probe.Table, probe.Columns, sqlgraph.NewFieldSpec(probe.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(probe.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Config(); ok {
		_spec.SetField(probe.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, probe.FieldConfig, value)
		})
	}
	if pu.mutation.ConfigCleared() {
		_spec.ClearField(probe.FieldConfig, field.TypeJSON)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(probe.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.LastHeartbeat(); ok {
		_spec.SetField(probe.FieldLastHeartbeat, field.TypeTime, value)
	}
	if pu.mutation.LastHeartbeatCleared() {
		_spec.ClearField(probe.FieldLastHeartbeat, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{probe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProbeUpdateOne is the builder for updating a single Probe entity.
type ProbeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProbeMutation
}

// SetStatus sets the "status" field.
func (puo *ProbeUpdateOne) SetStatus(ts types.ProbeStatus) *ProbeUpdateOne {
	puo.mutation.SetStatus(ts)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *ProbeUpdateOne) SetNillableStatus(ts *types.ProbeStatus) *ProbeUpdateOne {
	if ts != nil {
		puo.SetStatus(*ts)
	}
	return puo
}

// SetConfig sets the "config" field.
func (puo *ProbeUpdateOne) SetConfig(jm json.RawMessage) *ProbeUpdateOne {
	puo.mutation.SetConfig(jm)
	return puo
}

// AppendConfig appends jm to the "config" field.
func (puo *ProbeUpdateOne) AppendConfig(jm json.RawMessage) *ProbeUpdateOne {
	puo.mutation.AppendConfig(jm)
	return puo
}

// ClearConfig clears the value of the "config" field.
func (puo *ProbeUpdateOne) ClearConfig() *ProbeUpdateOne {
	puo.mutation.ClearConfig()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProbeUpdateOne) SetUpdatedAt(t time.Time) *ProbeUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (puo *ProbeUpdateOne) SetLastHeartbeat(t time.Time) *ProbeUpdateOne {
	puo.mutation.SetLastHeartbeat(t)
	return puo
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (puo *ProbeUpdateOne) SetNillableLastHeartbeat(t *time.Time) *ProbeUpdateOne {
	if t != nil {
		puo.SetLastHeartbeat(*t)
	}
	return puo
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (puo *ProbeUpdateOne) ClearLastHeartbeat() *ProbeUpdateOne {
	puo.mutation.ClearLastHeartbeat()
	return puo
}

// Mutation returns the ProbeMutation object of the builder.
func (puo *ProbeUpdateOne) Mutation() *ProbeMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProbeUpdate builder.
func (puo *ProbeUpdateOne) Where(ps ...predicate.Probe) *ProbeUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProbeUpdateOne) Select(field string, fields ...string) *ProbeUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Probe entity.
func (puo *ProbeUpdateOne) Save(ctx context.Context) (*Probe, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProbeUpdateOne) SaveX(ctx context.Context) *Probe {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProbeUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProbeUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProbeUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := probe.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProbeUpdateOne) check() error {
	if v, ok := puo.mutation.Status(); ok {
		if err := probe.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Probe.status": %w`, err)}
		}
	}
	return nil
}

func (puo *ProbeUpdateOne) sqlSave(ctx context.Context) (_node *Probe, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(probe.Table, probe.Columns, sqlgraph.NewFieldSpec(probe.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Probe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, probe.FieldID)
		for _, f := range fields {
			if !probe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != probe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(probe.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Config(); ok {
		_spec.SetField(probe.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, probe.FieldConfig, value)
		})
	}
	if puo.mutation.ConfigCleared() {
		_spec.ClearField(probe.FieldConfig, field.TypeJSON)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(probe.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.LastHeartbeat(); ok {
		_spec.SetField(probe.FieldLastHeartbeat, field.TypeTime, value)
	}
	if puo.mutation.LastHeartbeatCleared() {
		_spec.ClearField(probe.FieldLastHeartbeat, field.TypeTime)
	}
	_node = &Probe{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{probe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
