// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Nathene/SyntheticMonitor/ent/probe"
	"github.com/Nathene/SyntheticMonitor/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	probeFields := schema.Probe{}.Fields()
	_ = probeFields
	// probeDescCreatedAt is the schema descriptor for created_at field.
	probeDescCreatedAt := probeFields[3].Descriptor()
	// probe.DefaultCreatedAt holds the default value on creation for the created_at field.
	probe.DefaultCreatedAt = probeDescCreatedAt.Default.(func() time.Time)
	// probeDescUpdatedAt is the schema descriptor for updated_at field.
	probeDescUpdatedAt := probeFields[4].Descriptor()
	// probe.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	probe.DefaultUpdatedAt = probeDescUpdatedAt.Default.(func() time.Time)
	// probe.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	probe.UpdateDefaultUpdatedAt = probeDescUpdatedAt.UpdateDefault.(func() time.Time)
}
